In [1]:
import os
import pandas as pd
import numpy as np
import sklearn
from selenium import webdriver
import time
from basketball_reference_web_scraper import client
from basketball_reference_web_scraper.data import Location 
from basketball_reference_web_scraper import client

In [2]:
teamToIndex = {
    'ATL': 0,
    'BOS': 1,
    'BKN': 2,  
    'CHA': 3,
    'CHI': 4,
    'CLE': 5,
    'DAL': 6,
    'DEN': 7,
    'DET': 8,
    'GSW': 9,
    'HOU': 10,
    'IND': 11,
    'LAC': 12,
    'LAL': 13,
    'MEM': 14,
    'MIA': 15,
    'MIL': 16,
    'MIN': 17,
    'NOP': 18,
    'NYK': 19,
    'OKC': 20,
    'ORL': 21,
    'PHI': 22,
    'PHX': 23,
    'POR': 24,
    'SAC': 25,
    'SAS': 26,
    'TOR': 27,
    'UTA': 28,
    'WAS': 29,
}

# url = 'https://www.nba.com/stats/teams/traditional/?sort=TEAM_NAME&dir=-1&Season=2020-21&SeasonType=Regular%20Season'

# driver = webdriver.Chrome('/Users/nanboo/Desktop/CS4700/chromedriver')
# driver.get(url)




# select_box = driver.find_element_by_xpath("/html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select") 

# options = [x for x in select_box.find_elements_by_tag_name("option")]
# # this part is cool, because it searches the elements contained inside of select_box 
# # and then adds them to the list options if they have the tag name "options"

# years = []
# for element in options:
#     years.append(element.get_attribute("label"))
    
# years.pop(0)

# table = pd.DataFrame()

# for year in years:
#     url = 'https://www.nba.com/stats/teams/traditional/?sort=TEAM_NAME&dir=-1&Season='+year+'&SeasonType=Regular%20Season'
#     driver.get(url)
#     time.sleep(5)
#     html = driver.page_source

#     df = pd.read_html(html)
    
#     df = df[0]
#     df.drop(df.iloc[:, 28:], inplace = True, axis = 1)
#     df.drop(df.columns[0], inplace = True, axis = 1)
#     df['TEAM'] = df['TEAM'].replace(['New Jersey Nets'],'Brooklyn Nets')
#     df['TEAM'] = df['TEAM'].replace(['Los Angeles Clippers'],'LA Clippers')
#     df['TEAM'] = df['TEAM'].replace(['Vancouver Grizzlies'],'Memphis Grizzlies')
#     df['TEAM'] = df['TEAM'].replace(['Seattle SuperSonics'],'Oklahoma City Thunder')
#     df['TEAM'] = df['TEAM'].replace(['Washington Bullets'],'Washington Wizards')
#     df['TEAM'] = df['TEAM'].replace(['Charlotte Bobcats'],'Charlotte Hornets')
#     df['TEAM'] = df['TEAM'].replace(['New Orleans Hornets'],'New Orleans Pelicans')
#     df['TEAM'] = df['TEAM'].replace(['New Orleans/Oklahoma City Hornets'],'New Orleans Pelicans')
#     pelflag = 0
#     charflag = 0
    
#     for team in df['TEAM']:
#         if team == 'New Orleans Pelicans':
#             pelflag = 1
#         if team == 'Charlotte Hornets':
#             charflag = 1
    
#     pellist = [0] * 27
#     charlist = [0] * 27

#     if pelflag == 0:    
#         pellist[0] = 'New Orleans Pelicans'
#         df_length = len(df)
#         df.loc[df_length] = pellist
#     if charflag == 0:    
#         charlist[0] = 'Charlotte Hornets'
#         df_length = len(df)
#         df.loc[df_length] = charlist
    
    
#     df.sort_values(by=['TEAM'], inplace=True)
    
#     print(df)
    
#     table = table.append(df)
    

# table.to_csv(path_or_buf = '/Users/nanboo/Desktop/CS4700/games.csv')
df = pd.read_csv('/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/games.csv')
print(df)
df.to_csv(path_or_buf = '/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/games.csv', index=False)



                   TEAM  GP   W   L   WIN%   MIN    PTS   FGM   FGA   FG%  \
0         Atlanta Hawks  72  41  31  0.569  48.3  113.7  40.8  87.2  46.8   
1        Boston Celtics  72  36  36  0.500  48.3  112.6  41.5  88.9  46.6   
2         Brooklyn Nets  72  48  24  0.667  48.3  118.6  43.1  87.3  49.4   
3     Charlotte Hornets  72  33  39  0.458  48.2  109.5  39.9  87.8  45.5   
4         Chicago Bulls  72  31  41  0.431  48.3  110.7  42.2  88.6  47.6   
..                  ...  ..  ..  ..    ...   ...    ...   ...   ...   ...   
745    Sacramento Kings  82  34  48  0.415  48.4   96.4  36.6  80.6  45.4   
746   San Antonio Spurs  82  20  62  0.244  48.1   90.5  34.5  77.9  44.2   
747     Toronto Raptors  82  30  52  0.366  48.4   95.5  35.3  80.9  43.7   
748           Utah Jazz  82  64  18  0.780  48.4  103.1  38.2  75.8  50.4   
749  Washington Wizards  82  44  38  0.537  48.4   99.4  39.1  81.4  48.0   

     ...  DREB   REB   AST   TOV  STL  BLK  BLKA    PF   PFD  +/-  
0    ..

In [7]:
# df = pd.read_csv('/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/champions.csv')
# #print(df)
# #df.to_csv(path_or_buf = '/Users/nanboo/Desktop/CS4700/champions.csv', index=False)
# row=df.iloc[0]
# df.columns=row
# df=df.drop([0])
# df = df.loc[:, df.columns.notnull()]
# df.drop(df.index[25:], inplace = True, axis = 0)
# df.to_csv(path_or_buf = '/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/champions.csv')

In [8]:
df = pd.read_csv('/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/games.csv')
df.head()

TEAM  GP   W   L   WIN%   MIN    PTS   FGM   FGA   FG%  ...  \
0      Atlanta Hawks  72  41  31  0.569  48.3  113.7  40.8  87.2  46.8  ...   
1     Boston Celtics  72  36  36  0.500  48.3  112.6  41.5  88.9  46.6  ...   
2      Brooklyn Nets  72  48  24  0.667  48.3  118.6  43.1  87.3  49.4  ...   
3  Charlotte Hornets  72  33  39  0.458  48.2  109.5  39.9  87.8  45.5  ...   
4      Chicago Bulls  72  31  41  0.431  48.3  110.7  42.2  88.6  47.6  ...   

   DREB   REB   AST   TOV  STL  BLK  BLKA    PF   PFD  +/-  
0  35.1  45.6  24.1  13.2  7.0  4.8   5.0  19.3  19.8  2.3  
1  33.6  44.3  23.5  14.1  7.7  5.3   4.6  20.4  19.3  1.5  
2  35.5  44.4  26.8  13.5  6.7  5.3   4.6  19.0  18.9  4.5  
3  33.2  43.8  26.8  14.8  7.8  4.8   4.8  18.0  18.6 -1.9  
4  35.3  45.0  26.8  15.1  6.7  4.2   5.1  18.9  17.7 -0.9  

[5 rows x 27 columns]

In [9]:
df = pd.read_csv('/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/games.csv')
df.drop(['TEAM','GP','W','L'], inplace = True, axis = 1)
table = []
l = []
row = df.iloc[0].values.tolist();
l += row
for i in range(750):
    if i % 30 != 0:
        row = df.iloc[i].values.tolist();
        #print(row)
        l = l + row;
    elif i != 0:
        print(l)
        table.append(l)
        l = []
        l += df.iloc[i].values.tolist();
table.append(l)
print(table)   
dfn = pd.DataFrame(table)





dfn
dfn.to_csv('/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/champsAllStats.csv', header=False, index=False)

[0.569, 48.3, 113.7, 40.8, 87.2, 46.8, 12.4, 33.4, 37.3, 19.7, 24.2, 81.2, 10.6, 35.1, 45.6, 24.1, 13.2, 7.0, 4.8, 5.0, 19.3, 19.8, 2.3, 0.5, 48.3, 112.6, 41.5, 88.9, 46.6, 13.6, 36.4, 37.4, 16.1, 20.8, 77.5, 10.6, 33.6, 44.3, 23.5, 14.1, 7.7, 5.3, 4.6, 20.4, 19.3, 1.5, 0.667, 48.3, 118.6, 43.1, 87.3, 49.4, 14.2, 36.1, 39.2, 18.1, 22.5, 80.4, 8.9, 35.5, 44.4, 26.8, 13.5, 6.7, 5.3, 4.6, 19.0, 18.9, 4.5, 0.458, 48.2, 109.5, 39.9, 87.8, 45.5, 13.7, 37.0, 36.9, 15.9, 20.9, 76.1, 10.6, 33.2, 43.8, 26.8, 14.8, 7.8, 4.8, 4.8, 18.0, 18.6, -1.9, 0.431, 48.3, 110.7, 42.2, 88.6, 47.6, 12.6, 34.0, 37.0, 13.8, 17.5, 79.1, 9.6, 35.3, 45.0, 26.8, 15.1, 6.7, 4.2, 5.1, 18.9, 17.7, -0.9, 0.306, 48.4, 103.8, 38.6, 85.8, 45.0, 10.0, 29.7, 33.6, 16.7, 22.4, 74.3, 10.4, 32.3, 42.8, 23.8, 15.5, 7.8, 4.5, 5.9, 18.2, 20.2, -8.4, 0.583, 48.1, 112.4, 41.1, 87.3, 47.0, 13.8, 38.1, 36.2, 16.5, 21.2, 77.8, 9.1, 34.2, 43.3, 22.9, 12.1, 6.3, 4.3, 3.7, 19.4, 20.1, 2.3, 0.653, 48.6, 115.1, 43.3, 89.2, 48.5, 12.9, 34.2,

In [10]:
teamToIndex = {
    'Atlanta Hawks': 1,
    'Boston Celtics': 2,
    'Brooklyn Nets': 3,  
    'Charlotte Hornets': 4,
    'Chicago Bulls': 5,
    'Cleveland Cavaliers': 6,
    'Dallas Mavericks': 7,
    'Denver Nuggets': 8,
    'Detroit Pistons': 9,
    'Golden State Warriors': 10,
    'Houston Rockets': 11,
    'Indiana Pacers': 12,
    'LA Clippers': 13,
    'Los Angeles Lakers': 14,
    'Memphis Grizzlies': 15,
    'Miami Heat': 16,
    'Milwaukee Bucks': 17,
    'Minnesota Timberwolves': 18,
    'New Orleans Pelicans': 19,
    'New York Knicks': 20,
    'Oklahoma City Thunder': 21,
    'Orlando Magic': 22,
    'Philadelphia 76ers': 23,
    'Phoenix Suns': 24,
    'Portland Trail Blazers': 25,
    'Sacramento Kings': 26,
    'San Antonio Spurs': 27,
    'Toronto Raptors': 28,
    'Utah Jazz': 29,
    'Washington Wizards': 30,
}


champdf = pd.read_csv('/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/champions.csv')
l = []
for team in champdf["Champion"]:
    l.append(teamToIndex[team])
print(l)
print(len(l))
#champdf

[17, 14, 28, 10, 10, 6, 10, 27, 16, 16, 7, 14, 14, 2, 27, 16, 27, 9, 27, 14, 14, 14, 27, 5, 5]
25


In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split

X = dfn
y = np.asarray(l)
print(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_test)
print(y_test)
    
#training and predictions
clf = LinearRegression().fit(X_train, y_train)
#clf.fit(X_train,y_train)
predictionslin = clf.predict(X_test)

print(predictionslin)
predictionslin = np.rint(predictionslin)
print(predictionslin)
    
#checking to see percentage correct
ytestnp = y_test
totalsame = np.sum(ytestnp == predictionslin)
total = np.size(ytestnp)
percent = (totalsame)/total
print(percent)
#percents.append(percent)


[17 14 28 10 10  6 10 27 16 16  7 14 14  2 27 16 27  9 27 14 14 14 27  5
  5]
      0     1      2     3     4     5     6     7     8     9    ...   680  \
3   0.293  48.1  103.4  38.2  85.5  44.6  11.2  31.0  36.0  15.8  ...  33.1   
8   0.537  48.4   98.0  37.6  81.0  46.4   8.6  23.2  37.1  14.1  ...  32.3   
16  0.159  48.4   92.7  35.9  81.4  44.1   3.7  11.9  31.2  17.3  ...  29.0   

     681   682   683  684  685  686   687   688  689  
3   43.1  25.2  14.6  7.9  4.3  4.7  21.3  20.0  0.6  
8   43.2  21.6  15.1  7.3  4.6  4.4  20.5  19.1 -2.5  
16  42.8  19.1  14.3  8.7  4.2  5.0  22.0   0.0 -0.3  

[3 rows x 690 columns]
[10 16 27]
[13.34557793 15.76020485 10.62162802]
[13. 16. 11.]
0.3333333333333333


In [34]:
from sklearn.linear_model import Ridge

X = dfn
y = np.asarray(l)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(y_test)

for j in [0.1,0.5,1.0,10,100,300]:
    clf = Ridge(alpha=j,solver='auto').fit(X_train, y_train)
    #clf.fit(X_train,y_train)
    predictionslin = clf.predict(X_test)

    print(predictionslin)
    predictionslin = np.rint(predictionslin)
    print(predictionslin)

    #checking to see percentage correct
    ytestnp = y_test
    totalsame = np.sum(ytestnp == predictionslin)
    total = np.size(ytestnp)
    percent = (totalsame)/total
    print(percent)
    

[ 9 27 16 27  7]
[23.73309607 22.08222193 24.95775929 30.8503853  18.31485534]
[24. 22. 25. 31. 18.]
0.0
[23.7336544  22.08382417 24.9504744  30.83861222 18.31154584]
[24. 22. 25. 31. 18.]
0.0
[23.73434318 22.08581521 24.94138487 30.82392402 18.30741854]
[24. 22. 25. 31. 18.]
0.0
[23.74505648 22.11948357 24.78085677 30.56476532 18.23490168]
[24. 22. 25. 31. 18.]
0.0
[23.71988462 22.28414728 23.43960327 28.4169498  17.65778679]
[24. 22. 23. 28. 18.]
0.0
[23.26639987 22.10628174 21.51011804 25.37659425 16.92233034]
[23. 22. 22. 25. 17.]
0.0


In [12]:
#lets drop features
df = pd.read_csv('/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/games.csv')
df.drop(['TEAM','GP','W','L','MIN','PTS','FGM','3PM','3PA','FGA','FTM','FTA','BLKA'], inplace = True, axis = 1)
table = []
l = []
row = df.iloc[0].values.tolist();
l += row
for i in range(750):
    if i % 30 != 0:
        row = df.iloc[i].values.tolist();
        #print(row)
        l = l + row;
    elif i != 0:
        print(l)
        table.append(l)
        l = []
        l += df.iloc[i].values.tolist();
table.append(l)
print(table)   
dfn = pd.DataFrame(table)
dfn

[0.569, 46.8, 37.3, 81.2, 10.6, 35.1, 45.6, 24.1, 13.2, 7.0, 4.8, 19.3, 19.8, 2.3, 0.5, 46.6, 37.4, 77.5, 10.6, 33.6, 44.3, 23.5, 14.1, 7.7, 5.3, 20.4, 19.3, 1.5, 0.667, 49.4, 39.2, 80.4, 8.9, 35.5, 44.4, 26.8, 13.5, 6.7, 5.3, 19.0, 18.9, 4.5, 0.458, 45.5, 36.9, 76.1, 10.6, 33.2, 43.8, 26.8, 14.8, 7.8, 4.8, 18.0, 18.6, -1.9, 0.431, 47.6, 37.0, 79.1, 9.6, 35.3, 45.0, 26.8, 15.1, 6.7, 4.2, 18.9, 17.7, -0.9, 0.306, 45.0, 33.6, 74.3, 10.4, 32.3, 42.8, 23.8, 15.5, 7.8, 4.5, 18.2, 20.2, -8.4, 0.583, 47.0, 36.2, 77.8, 9.1, 34.2, 43.3, 22.9, 12.1, 6.3, 4.3, 19.4, 20.1, 2.3, 0.653, 48.5, 37.7, 80.3, 10.5, 33.9, 44.4, 26.8, 13.5, 8.1, 4.5, 19.1, 19.2, 4.9, 0.278, 45.2, 35.1, 75.9, 9.6, 33.1, 42.7, 24.2, 14.9, 7.4, 5.2, 20.5, 20.4, -4.5, 0.542, 46.8, 37.6, 78.5, 8.0, 35.1, 43.0, 27.7, 15.0, 8.2, 4.8, 21.2, 19.5, 1.1, 0.236, 44.4, 33.9, 74.0, 9.3, 33.3, 42.6, 23.6, 14.7, 7.6, 5.0, 19.5, 19.3, -7.9, 0.472, 47.4, 36.4, 79.2, 9.0, 33.7, 42.7, 27.4, 13.5, 8.5, 6.4, 20.2, 18.1, 0.0, 0.653, 48.2, 41.1, 

0     1     2     3     4     5     6     7     8    9    ...   410  \
0   0.569  46.8  37.3  81.2  10.6  35.1  45.6  24.1  13.2  7.0  ...   9.7   
1   0.299  44.9  33.3  79.0   9.9  33.4  43.3  24.0  16.2  7.8  ...  10.2   
2   0.354  45.1  35.2  75.2  11.6  34.5  46.1  25.8  17.0  8.2  ...   9.7   
3   0.293  44.6  36.0  78.5   9.1  32.8  41.9  23.7  15.5  7.8  ...  10.0   
4   0.524  45.1  34.1  72.8  10.3  34.1  44.3  23.6  15.8  8.2  ...  10.3   
5   0.585  45.8  35.0  78.3   8.3  33.8  42.1  25.6  15.0  9.1  ...   9.1   
6   0.732  46.6  38.0  77.8   8.7  31.8  40.6  25.7  14.2  9.1  ...  10.5   
7   0.463  45.8  36.3  78.1   8.7  31.3  40.0  24.9  15.3  8.3  ...  10.8   
8   0.537  46.4  37.1  71.5   9.2  31.6  40.9  24.5  14.9  8.1  ...  10.8   
9   0.606  45.4  37.0  74.0   9.9  31.3  41.2  22.4  14.0  8.1  ...  11.7   
10  0.537  46.2  35.2  77.9   9.3  30.0  39.3  22.0  13.6  6.1  ...  12.4   
11  0.646  46.8  36.0  75.9  11.8  29.9  41.7  21.8  12.0  7.2  ...  11.8   
12  0.573  45.8  36.6  73.7  10.6  29.4  40.0  20.2  12.8  7.4  ...  11.7   
13  0.451  45.4  35.6  77.2  12.3  29.9  42.2  22.0  14.9  7.3  ...  12.3   
14  0.366  44.4  32.9  76.1  11.9  28.2  40.1  19.2  15.9  7.4  ...  12.2   
15  0.317  45.4  36.7  75.0  13.0  27.2  40.3  19.8  15.7  7.2  ...  12.6   
16  0.159  44.1  31.2  71.1  13.4  28.5  41.9  19.7  16.1  7.7  ...  13.8   
17  0.341  43.3  33.5  77.6  12.1  30.6  42.7  20.1  16.5  7.6  ...  13.6   
18  0.427  44.4  35.2  79.3  11.4  31.2  42.6  20.5  16.7  7.5  ...  11.2   
19  0.402  43.9  35.4  76.5  11.6  29.8  41.5  20.2  15.5  8.1  ...  12.9   
20  0.305  43.1  35.7  75.9  12.5  30.4  42.9  19.0  16.7  7.7  ...  12.4   
21  0.341  44.1  31.7  74.3  14.0  31.3  45.3  18.9  15.4  6.1  ...  13.0   
22  0.620  40.9  30.6  73.1  13.5  30.0  43.5  15.6  14.9  6.9  ...  11.9   
23  0.610  45.5  33.2  75.6  13.5  29.5  43.0  19.1  14.8  7.9  ...  13.7   
24  0.683  44.6  36.0  76.3  12.5  28.7  41.1  19.0  15.0  8.5  ...  12.3   

     411   412   413   414  415  416   417   418  419  
0   35.5  45.2  25.5  14.4  7.3  4.1  21.6  22.0 -1.8  
1   31.9  42.0  25.0  14.2  8.0  4.3  22.7  22.2 -4.7  
2   32.7  42.4  26.3  14.1  8.3  4.6  20.7  21.2 -2.9  
3   33.1  43.1  25.2  14.6  7.9  4.3  21.3  20.0  0.6  
4   32.6  42.9  23.9  14.2  8.5  4.1  21.3  19.8  1.8  
5   32.8  41.8  24.5  14.5  8.6  3.9  20.8  20.1 -0.5  
6   34.2  44.7  24.0  15.0  7.3  4.6  20.8  19.6  0.7  
7   31.4  42.2  23.3  14.7  8.1  4.6  20.4  19.5  1.3  
8   32.3  43.2  21.6  15.1  7.3  4.6  20.5  19.1 -2.5  
9   29.9  41.7  19.1  15.3  8.0  6.3  21.3  18.7 -4.8  
10  29.0  41.3  19.4  15.3  8.1  6.1  22.6  20.3 -7.4  
11  30.0  41.8  19.0  14.9  6.0  5.1  21.4  20.5 -4.8  
12  28.4  40.1  20.0  14.0  7.5  4.5  20.5  20.0 -7.5  
13  29.3  41.6  19.6  13.2  7.7  4.8  19.6  20.2 -0.3  
14  29.0  41.2  20.2  13.8  7.7  4.6  22.2  23.5 -0.5  
15  28.6  41.2  18.6  13.9  8.0  4.1  22.6  25.0  1.9  
16  29.0  42.8  19.1  14.3  8.7  4.2  22.0   0.0 -0.3  
17  29.2  42.8  18.7  17.5  8.9  5.0  20.9   0.0 -5.6  
18  29.2  40.4  19.7  13.4  7.6  4.8  20.0   0.0 -1.0  
19  29.2  42.0  20.9  13.0  7.0  4.3  21.5   0.1 -1.4  
20  28.9  41.3  20.1  17.0  7.7  4.7  23.3   0.1 -6.7  
21  29.7  42.7  21.6  16.1  7.2  4.7  26.2   2.7 -3.3  
22  28.1  40.0  21.3  14.7  7.9  3.9  23.0   0.1 -2.2  
23  28.5  42.2  23.2  14.1  8.4  4.6  22.4   0.2  0.6  
24  29.5  41.8  23.4  15.7  8.7  4.9  22.1   0.2  1.6  

[25 rows x 420 columns]

In [13]:
X = dfn

champdf = pd.read_csv('/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/champions.csv')
l = []
for team in champdf["Champion"]:
    l.append(teamToIndex[team])
print(l)
print(len(l))

y = np.asarray(l)
print(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_test)
print(y_test)
    
#training and predictions
clf = LinearRegression().fit(X_train, y_train)
#clf.fit(X_train,y_train)
predictionslin = clf.predict(X_test)

print(predictionslin)
predictionslin = np.rint(predictionslin)
print(predictionslin)
    
#checking to see percentage correct
ytestnp = y_test
totalsame = np.sum(ytestnp == predictionslin)
total = np.size(ytestnp)
percent = (totalsame)/total
print(percent)

[17, 14, 28, 10, 10, 6, 10, 27, 16, 16, 7, 14, 14, 2, 27, 16, 27, 9, 27, 14, 14, 14, 27, 5, 5]
25
[17 14 28 10 10  6 10 27 16 16  7 14 14  2 27 16 27  9 27 14 14 14 27  5
  5]
      0     1     2     3     4     5     6     7     8    9    ...   410  \
9   0.606  45.4  37.0  74.0   9.9  31.3  41.2  22.4  14.0  8.1  ...  11.7   
23  0.610  45.5  33.2  75.6  13.5  29.5  43.0  19.1  14.8  7.9  ...  13.7   
19  0.402  43.9  35.4  76.5  11.6  29.8  41.5  20.2  15.5  8.1  ...  12.9   

     411   412   413   414  415  416   417   418  419  
9   29.9  41.7  19.1  15.3  8.0  6.3  21.3  18.7 -4.8  
23  28.5  42.2  23.2  14.1  8.4  4.6  22.4   0.2  0.6  
19  29.2  42.0  20.9  13.0  7.0  4.3  21.5   0.1 -1.4  

[3 rows x 420 columns]
[16  5 14]
[13.40345435 18.28997485 11.10607384]
[13. 18. 11.]
0.0


In [251]:
#lets preprocess
normalized_df=(dfn-dfn.mean())/dfn.std()

X = normalized_df
y = np.asarray(l)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

print(y_test)
    
#training and predictions
clf = LinearRegression().fit(X_train, y_train)
#clf.fit(X_train,y_train)
predictionslin = clf.predict(X_test)

print(predictionslin)
predictionslin = np.rint(predictionslin)
print(predictionslin)
    
#checking to see percentage correct
ytestnp = y_test
totalsame = np.sum(ytestnp == predictionslin)
total = np.size(ytestnp)
percent = (totalsame)/total
print(percent)

[14 16 14]
[17.78974273 10.20631551  6.72960538]
[18. 10.  7.]
0.0


In [180]:
#using SVM

X = dfn
y = np.asarray(l)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print(y_test)

from sklearn.svm import SVC
clf = SVC(C=100,kernel='rbf')
clf.fit(X_train,y_train)
predictionssvm = clf.predict(X_test)

clf2 = SVC(C=100,kernel='poly')
clf2.fit(X_train,y_train)
predictionssvm2 = clf2.predict(X_test)

print(predictionssvm)
print(predictionssvm2)
    
#checking to see percentage correct
ytestnp = y_test
totalsame = np.sum(ytestnp == predictionssvm)
total = np.size(ytestnp)
percent = (totalsame)/total
print(percent)

ytestnp = y_test
totalsame = np.sum(ytestnp == predictionssvm2)
total = np.size(ytestnp)
percent = (totalsame)/total
print(percent)

[14 27 16 14 14 10 16  9]
[27  5 27 14 27 27 27 27]
[ 7  5 27 14  2 27  7 27]
0.125
0.125


In [250]:
#using Random Forest

X = dfn
y = np.asarray(l)
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print(y_test)

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
clfRF = RandomForestClassifier(random_state=0)
clfRF.fit(X_train,y_train)
predictionsdeep = clfRF.predict(X_test)
print(predictionsdeep)

#checking to see percentage correct
ytestnp = y_test
totalsame = np.sum(ytestnp == predictionsdeep)
total = np.size(ytestnp)
percent = (totalsame)/total
print(percent)

[17 14 28 10 10  6 10 27 16 16  7 14 14  2 27 16 27  9 27 14 14 14 27  5
  5]
[ 9 27 14 16 17 27 14  5]
[27 14 14 27 10 27 14 27]
0.375


In [71]:
#using Neural Net
from sklearn.neural_network import MLPClassifier

X = dfn
y = np.asarray(l)
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print(y_test)

clf = MLPClassifier(max_iter=500, activation= 'relu', alpha= 0.05, hidden_layer_sizes= (210, 30), learning_rate= 'constant', solver= 'adam').fit(X_train, y_train)
predictionsneural = clf.predict(X_test)
print(predictionsneural)

#checking to see percentage correct
ytestnp = y_test
totalsame = np.sum(ytestnp == predictionsneural)
total = np.size(ytestnp)
percent = (totalsame)/total
print(percent)

[17 14 28 10 10  6 10 27 16 16  7 14 14  2 27 16 27  9 27 14 14 14 27  5
  5]
[14 14  5  9 14 27 16 14]
[27 27 27 14 27 27 27 14]
0.25


In [62]:
X = dfn
y = np.asarray(l)

parameter_space = {
    'hidden_layer_sizes': [(210,),(210,105),(210,30)],
    'activation': ['tanh','relu'],
    'solver': ['sgd', 'lbfgs','adam'],
    'alpha': [0.0001,0.05],
    'learning_rate': ['constant','adaptive'],
}

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(max_iter=500)

from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(mlp, parameter_space, n_jobs=-1, cv=3)
clf.fit(X_train, y_train)

# Best parameter set
print('Best parameters found:\n', clf.best_params_)

# All results
means = clf.cv_results_['mean_test_score']
stds = clf.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, clf.cv_results_['params']):
    print("%0.3f (+/-%0.03f) for %r" % (mean, std * 2, params))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


Best parameters found:
 {'activation': 'relu', 'alpha': 0.05, 'hidden_layer_sizes': (210, 30), 'learning_rate': 'constant', 'solver': 'adam'}
0.067 (+/-0.189) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (210,), 'learning_rate': 'constant', 'solver': 'sgd'}
0.178 (+/-0.274) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (210,), 'learning_rate': 'constant', 'solver': 'lbfgs'}
0.244 (+/-0.220) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (210,), 'learning_rate': 'constant', 'solver': 'adam'}
0.000 (+/-0.000) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (210,), 'learning_rate': 'adaptive', 'solver': 'sgd'}
0.133 (+/-0.377) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (210,), 'learning_rate': 'adaptive', 'solver': 'lbfgs'}
0.056 (+/-0.157) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (210,), 'learning_rate': 'adaptive', 'solver': 'adam'}
0.056 (+/-0.157) for {'activat

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [40]:
#hyper parameter tuning on SVM

X_goated= X_train

percents = []
C_range = np.logspace(-2, 3, 5)
print(C_range)
gamma_range = np.logspace(-2, 1, 5)
print(gamma_range)
testSize = [.1,.2,.3,.4,.5]

for k in range(len(testSize)):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=testSize[k])
    for i in range(np.size(C_range)):
            #training and predictions
            clf = SVC(C=C_range[i],kernel='poly')            
            clf.fit(X_train,y_train)
            predictionssvm = clf.predict(X_test)
            print(predictionssvm)

            #checking to see percentage correct
            totalsame = np.sum(y_test == predictionssvm)
            total = np.size(y_test)
            percent = (totalsame)/total
            percents.append(percent)

maximumper = max(percents)
maxindex = percents.index(maximumper)
print(maxindex)
perss = pd.DataFrame(percents)
perss

[1.00000000e-02 1.77827941e-01 3.16227766e+00 5.62341325e+01
 1.00000000e+03]
[ 0.01        0.05623413  0.31622777  1.77827941 10.        ]


NameError: name 'SVC' is not defined

In [55]:
#boosting
from sklearn.ensemble import BaggingClassifier
X = dfn
y = np.asarray(l)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print(y_test)

from sklearn.svm import SVC

bagging = BaggingClassifier(base_estimator= SVC(C=1000,kernel='poly'),max_samples=0.8,  n_estimators=1000)
bagging.fit(X_train, y_train)
baggingpred = bagging.predict(X_test)

print(baggingpred)    
#checking to see percentage correct
ytestnp = y_test
totalsame = np.sum(ytestnp == baggingpred)
total = np.size(ytestnp)
percent = (totalsame)/total
print(percent)



[ 2 14 16 27  5  6 27 27]
[10 10 10  9  5  9  5  7]
0.125


In [75]:
#bagging using Neural Net
from sklearn.neural_network import MLPClassifier

X = dfn
y = np.asarray(l)
print(y)



#for i in range(100):
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print(y_test)
bagging = BaggingClassifier(base_estimator= MLPClassifier(max_iter=1000, alpha= 0.05, hidden_layer_sizes= (210, 30)),max_samples=.8,  n_estimators=100)
bagging.fit(X_train, y_train)
baggingpred = bagging.predict(X_test)
print(baggingpred)

#checking to see percentage correct
ytestnp = y_test
totalsame = np.sum(ytestnp == baggingpred)
total = np.size(ytestnp)
percent = (totalsame)/total
print(percent)



#print(percents)
#avgCorrect= sum(percents)/len(percents)

[17 14 28 10 10  6 10 27 16 16  7 14 14  2 27 16 27  9 27 14 14 14 27  5
  5]
[27 28 27 14 16 27 27  6]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 10  9 17  7 14 16 10]
0.0


In [72]:
percents = []
trains = []
X = dfn
y = np.asarray(l)
print(y)



for i in range(100):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    print(y_test)
    bagging = BaggingClassifier(base_estimator= MLPClassifier(max_iter=1000, alpha= 0.05, hidden_layer_sizes= (210, 30)),max_samples=.8,  n_estimators=100)
    bagging.fit(X_train, y_train)
    baggingpred = bagging.predict(X_test)
    print(baggingpred)

    #checking to see percentage correct
    ytestnp = y_test
    totalsame = np.sum(ytestnp == baggingpred)
    total = np.size(ytestnp)
    percent = (totalsame)/total
    print(percent)
    percents.append(percent)
    trains.append(X_train)

print(percents)
avgCorrect= sum(percents)/len(percents)
print(avgCorrect)


# [0.375, 0.375, 0.375, 0.0, 0.25, 0.0, 0.25, 0.0, 0.375,
#  0.125, 0.125, 0.375, 0.625, 0.25, 0.25, 0.625, 0.25, 
#  0.375, 0.125, 0.25, 0.375, 0.0, 0.5, 0.5, 0.375, 0.25, 
#  0.25, 0.5, 0.25, 0.25, 0.25, 0.375, 0.5, 0.375, 0.5, 0.375, 
#  0.125, 0.125, 0.5, 0.375, 0.25, 0.25, 0.25, 0.5, 0.25, 0.25, 
#  0.5, 0.125, 0.0, 0.125, 0.125, 0.125, 0.375, 0.25, 0.25, 0.5, 
#  0.25, 0.125, 0.125, 0.125, 0.5, 0.375, 0.25, 0.5, 0.25, 
#  0.375, 0.375, 0.125, 0.25, 0.25, 0.125, 0.125, 0.375, 0.5, 
#  0.375, 0.25, 0.25, 0.125, 0.375, 0.125, 0.25, 0.375, 0.25, 
#  0.25, 0.25, 0.25, 0.25, 0.375, 0.375, 0.375, 0.5, 0.125, 
#  0.375, 0.25, 0.25, 0.625, 0.25, 0.125, 0.125, 0.0]
# 0.28375

[17 14 28 10 10  6 10 27 16 16  7 14 14  2 27 16 27  9 27 14 14 14 27  5
  5]
[14  2 27 27 14 27  5 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 14 14 14 14  5 14]
0.375
[10 28  5 27  9 10  6 14]
[10 10  5 27 27 27 10 16]
0.375
[14 14 16  2 14 28 27 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14 14 27 14 10 10 27  7]
0.375
[27 17 16 14 14 27 10 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 27  2  7 16  6  6]
0.0
[ 5  6  5 14 14 27 27 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[27 10 27 14  7 27 16  2]
0.25
[27  5 10  5 27 10  2 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 28 14 14  6 14 27]
0.0
[14 14 28  5 14 27 17 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[27 27 10  5 14  9 10 27]
0.25
[10 27 16  2 27  5 27 27]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 6 16  7 14 16 14  9 14]
0.0
[14 10 14  9 17 14 16 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[ 7  6  2 27 14 14 16 14]
0.375
[ 5 14  7 27 14 17 14  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[27 14 16 10 27 14 27 27]
0.125
[27  2 27 27 27 14 14 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14 14  9 14 14 28 14 14]
0.125
[27 17 14 14 14 14  9 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[27 10 14 28  2 14 27  7]
0.375
[10 28 14 10 14 27 16  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[ 6 10 14  6 14 27 16  5]
0.625
[28 17 27  7 10 10 14  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 14 16 16  6  6 14  5]
0.25
[ 7  9 16  5 16 27 27 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 27 14  5 14 14 14 14]
0.25
[14 27 14 16 28 10 14 14]
[14  9 17 16 10 10 14 14]
0.625
[27 14 10 27 27 16  5 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[16 14  6 14  9  7  5 27]
0.25
[10 27 28 14 17 16 14 27]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 14 14 14 14 14 14  5]
0.375
[ 5 14  2 16  5 14 14  6]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[27 27 27  7 27 27 14 10]
0.125
[10 27 27 14  5 14 27 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[28 14 16 14  5 28  9  6]
0.25
[27 27  2 10 27  9 14  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[16 14 14 10 14 14 14  5]
0.375
[10  6  9 10 27 10 16 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[28 16 27 16 16 16 27 28]
0.0
[16 27 28 14  5 17 14  2]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[16 16 10 14  5 14 14 14]
0.5
[27 14  5 14 14 10 14 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[ 9 28  5 27 14  6 14 10]
0.5
[14 17 16 14  6  9 28 27]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 16 14 10 27 10 16]
0.375
[27 27 14  2 27 10  7 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 9 14 14 14 14 10 16 27]
0.25
[ 6  7 27 28 14 27 17 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 16  9 10 14 16 14 14]
0.25
[28  9 14 17 27  5 10 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[10 27 16 16 27  5 10 14]
0.5
[ 2 27 10 27 27 27 14 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 10 16 16 14 28 16]
0.25
[27 10  2 27 17 14  6 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 28 14 14 14 14 10 16]
0.25
[16 27 14  2  5 17 14  6]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 14 14 27 14 14 10]
0.25
[14 28  6  5 10 16 14 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14 10 10  5 27 27 16 14]
0.375
[14  5 27 10  7 14 14 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[28  5 27  6 16 27 14 14]
0.5
[10 14  5  5 16  7 27 28]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 14 27 27 16 14  9 10]
0.375
[14 27 16 16  5 14  7 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 27 16 14 14 14 14]
0.5
[27 16 17 14 27  5 27 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 9 27 14 14 10  5 14 14]
0.375
[27  5 27 27 27 10  6  9]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14 14 10 14 14 10 10 14]
0.125
[14 27 17 27  7 10 27 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[28 16 16 14 16  6  9 10]
0.125
[10 16 27  7 14 16  6  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 16 14 14 14 14 10  5]
0.5
[10 17 27 14 27 16 14  2]
[10 10 14 28 10 16 14 10]
0.375
[14 16 27 10 10 14 27  9]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14  7 16  6  6 14 14 27]
0.25
[10 14  9 14 16  2 27 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 6 27 27 14 16 14 16 28]
0.25
[16  7 14  9  2 14 27 27]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[16 14 27 27 14 27 27 16]
0.25
[27  7 16 28 14 14 27 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[16 16 16 10 14 14  9 14]
0.5
[10 10 14 16 14  9 16  7]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[28  6 28 27 14 27 16 16]
0.25
[10 28 27 27 14 27  7 16]
[ 6 10 14  6 14 16 14 16]
0.25
[ 6 14  5 27 27 16 28 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 14  5 14 27 16 10 14]
0.5
[ 6 14  9  5  2 27 14 17]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 14 27 14 14 14 28 10]
0.125
[27  5 16 16 28 14  5 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14  7 27 10 17 14 27]
0.0
[10  6 10 14 17  7  9 27]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[28 10 10 28 16 16 27 14]
0.125
[14  9  5 28 14 10  7  2]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[27 27 27 10 27 10 16 14]
0.125
[ 9 14 14 27 28 27 10  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14  7  7 14 14 14 10 14]
0.125
[16 16 27 14 14 27  9 28]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 7 10 14 14 14 27 27 10]
0.375
[27 16 14  5 14 17 16 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14 14 14  5 27 14  7  6]
0.25
[27 14 17 16 10 14 14 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 5 28 10  7  6 14 14 27]
0.25
[16 17 14  9 14 27 27 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[16 10 14 27 28 10 27 14]
0.5
[28 27  6 27 16 10 14 17]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 10 14  7 10 14 14]
0.25
[14  5  5 27 27 10  7 16]
[28 14 14  9 14 10 16 27]
0.125
[16 16 10 27 27 14 28 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 7 27  6 14  9 14 14 14]
0.125
[27 27  9 16  6 14  2  7]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 27 27 10 14 14 16]
0.125
[27 14 14 14  6 14  5 17]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[27 14 28 14 10 14 27 16]
0.5
[14 27  2 27 14  6 14 14]
[14 10 14  5 14 10 14 16]
0.375
[ 2 10  6 14 28 16 14 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 10 10 14 10  7 17 27]
0.25
[10 14 16 16  2  5  7 14]
[ 6 14 16 27 27  5 14 14]
0.5
[16 10 27  6 27 16 14 17]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 7 10  9 10 14 27 14 14]
0.25
[ 7 14  9  5 10  6 27 17]
[16 14 27  5 10 10 16 14]
0.375
[27 10  6 14 27 10 17  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[16 10 10 14 16 28 14  5]
0.375
[16 27 10 14 16 10 14 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14 14  6 27  7  6 14 28]
0.125
[14 10 27 16  2 27  7  9]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14  6  6 16 14 16 16 27]
0.25
[27 16 16  2 27  5 14 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 10  7 14  9  5 14 28]
0.25
[ 5 17 16 27 14  2  5 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[27 14 14 14 14 14 27  7]
0.125
[28 27 10 14 16 10 14 27]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 14  6 17 27  6 14 16]
0.125
[14 14  9  7 10 27  5 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14 16 27 16  6 27  5  6]
0.375
[14  6 16 16  5 14 10 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 27 27  7  5 14 27 10]
0.5
[ 5  7 28 17 16 10 14 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 5 14 14 14 16 14 14  6]
0.375
[27 16 27 28 10 14  6  9]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 27 27 10 10 17 10 27]
0.25
[ 5 17 28 10 27 14  2 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 5 16 10  6  9 14 14 16]
0.25
[27 27 27  7 17 16  6 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14  9 10 14 14 14 10 16]
0.125
[28 14  7 27 10 27 16 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[10 17 16 14 10 10 16 14]
0.375
[16 14 14  7  5 14 28  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[27  2 14 16 27 16 10 27]
0.125
[16  2  7 14 14 14 27 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[16 27 14 14 27 27 10 27]
0.25
[27 14 17  2 14 14 27  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 16 27 14 16 10  5]
0.375
[ 2 28 10 16 27 10 27 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14  6 14 14 14 27 16]
0.25
[17 28 27 10 16 10 27 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 14 16 14  7  6 27 14]
0.25
[16 10 14 17  7 27  5 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 10 14 14 14 10 27 10]
0.25
[ 5 16 14  5 10 14 10 27]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 27 14 14  6 28 28 27]
0.25
[ 7 27 27 14  5 17 10  9]
[16 14 10 14 14 14 10 27]
0.25
[ 9 27  5 14 28 16  6 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[27  2  5 14 10 14 10 14]
0.375
[ 9 14 14  5 14 27  7 10]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[27 16  2  5 14 10 16 10]
0.375
[14  6  5 27 10  2  5 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[28 10 27 27 10 14 27 14]
0.375
[16 27  5 14  6 17 14  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[16 27 27 14 10 14 14 27]
0.5
[10  9 28 27 27 10 17 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 6 27 14 14 14  6 14 16]
0.125
[14 17 14  9 27 10 14  5]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[27 14 14 27 16 10 14 27]
0.375
[27  5 10 27 14 28 14 17]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[16  5  6  9 14 10 16 16]
0.25
[27 16 14 27  2 10 27 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[16 16 28  9 14  6  6 14]
0.25
[ 6  5 10 14 14 28 27 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[10  5 10 14 14 10 14 14]
0.625
[14 16 16 27 27 10 16  2]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10

[14  7 27  9 10 10 10 14]
0.25
[ 2 14 17  7 10 14 14 16]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[27 27 28 16  6 28 27 16]
0.125
[16 16 14 14 27  5 14 14]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[ 7 10  2 28 10 27 14  7]
0.125
[27 14 28 16 27 27 16 17]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


[14 10 10 27  9 14  7 10]
0.0
[0.375, 0.375, 0.375, 0.0, 0.25, 0.0, 0.25, 0.0, 0.375, 0.125, 0.125, 0.375, 0.625, 0.25, 0.25, 0.625, 0.25, 0.375, 0.125, 0.25, 0.375, 0.0, 0.5, 0.5, 0.375, 0.25, 0.25, 0.5, 0.25, 0.25, 0.25, 0.375, 0.5, 0.375, 0.5, 0.375, 0.125, 0.125, 0.5, 0.375, 0.25, 0.25, 0.25, 0.5, 0.25, 0.25, 0.5, 0.125, 0.0, 0.125, 0.125, 0.125, 0.375, 0.25, 0.25, 0.5, 0.25, 0.125, 0.125, 0.125, 0.5, 0.375, 0.25, 0.5, 0.25, 0.375, 0.375, 0.125, 0.25, 0.25, 0.125, 0.125, 0.375, 0.5, 0.375, 0.25, 0.25, 0.125, 0.375, 0.125, 0.25, 0.375, 0.25, 0.25, 0.25, 0.25, 0.25, 0.375, 0.375, 0.375, 0.5, 0.125, 0.375, 0.25, 0.25, 0.625, 0.25, 0.125, 0.125, 0.0]
0.28375


In [78]:
dfgoat = trains[95]
dfgoat.to_csv(path_or_buf = '/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/goatedTrain.csv', index=False)
dfgoat

0     1     2     3     4     5     6     7     8    9    ...   410  \
4   0.524  45.1  34.1  72.8  10.3  34.1  44.3  23.6  15.8  8.2  ...  10.3   
15  0.317  45.4  36.7  75.0  13.0  27.2  40.3  19.8  15.7  7.2  ...  12.6   
21  0.341  44.1  31.7  74.3  14.0  31.3  45.3  18.9  15.4  6.1  ...  13.0   
8   0.537  46.4  37.1  71.5   9.2  31.6  40.9  24.5  14.9  8.1  ...  10.8   
13  0.451  45.4  35.6  77.2  12.3  29.9  42.2  22.0  14.9  7.3  ...  12.3   
17  0.341  43.3  33.5  77.6  12.1  30.6  42.7  20.1  16.5  7.6  ...  13.6   
7   0.463  45.8  36.3  78.1   8.7  31.3  40.0  24.9  15.3  8.3  ...  10.8   
14  0.366  44.4  32.9  76.1  11.9  28.2  40.1  19.2  15.9  7.4  ...  12.2   
12  0.573  45.8  36.6  73.7  10.6  29.4  40.0  20.2  12.8  7.4  ...  11.7   
10  0.537  46.2  35.2  77.9   9.3  30.0  39.3  22.0  13.6  6.1  ...  12.4   
1   0.299  44.9  33.3  79.0   9.9  33.4  43.3  24.0  16.2  7.8  ...  10.2   
0   0.569  46.8  37.3  81.2  10.6  35.1  45.6  24.1  13.2  7.0  ...   9.7   
16  0.159  44.1  31.2  71.1  13.4  28.5  41.9  19.7  16.1  7.7  ...  13.8   
23  0.610  45.5  33.2  75.6  13.5  29.5  43.0  19.1  14.8  7.9  ...  13.7   
9   0.606  45.4  37.0  74.0   9.9  31.3  41.2  22.4  14.0  8.1  ...  11.7   
18  0.427  44.4  35.2  79.3  11.4  31.2  42.6  20.5  16.7  7.5  ...  11.2   
3   0.293  44.6  36.0  78.5   9.1  32.8  41.9  23.7  15.5  7.8  ...  10.0   

     411   412   413   414  415  416   417   418  419  
4   32.6  42.9  23.9  14.2  8.5  4.1  21.3  19.8  1.8  
15  28.6  41.2  18.6  13.9  8.0  4.1  22.6  25.0  1.9  
21  29.7  42.7  21.6  16.1  7.2  4.7  26.2   2.7 -3.3  
8   32.3  43.2  21.6  15.1  7.3  4.6  20.5  19.1 -2.5  
13  29.3  41.6  19.6  13.2  7.7  4.8  19.6  20.2 -0.3  
17  29.2  42.8  18.7  17.5  8.9  5.0  20.9   0.0 -5.6  
7   31.4  42.2  23.3  14.7  8.1  4.6  20.4  19.5  1.3  
14  29.0  41.2  20.2  13.8  7.7  4.6  22.2  23.5 -0.5  
12  28.4  40.1  20.0  14.0  7.5  4.5  20.5  20.0 -7.5  
10  29.0  41.3  19.4  15.3  8.1  6.1  22.6  20.3 -7.4  
1   31.9  42.0  25.0  14.2  8.0  4.3  22.7  22.2 -4.7  
0   35.5  45.2  25.5  14.4  7.3  4.1  21.6  22.0 -1.8  
16  29.0  42.8  19.1  14.3  8.7  4.2  22.0   0.0 -0.3  
23  28.5  42.2  23.2  14.1  8.4  4.6  22.4   0.2  0.6  
9   29.9  41.7  19.1  15.3  8.0  6.3  21.3  18.7 -4.8  
18  29.2  40.4  19.7  13.4  7.6  4.8  20.0   0.0 -1.0  
3   33.1  43.1  25.2  14.6  7.9  4.3  21.3  20.0  0.6  

[17 rows x 420 columns]

In [74]:
percents[95]

0.625

In [77]:
dfsame = pd.merge(trains[95], dfn, how='inner')
dfsame

0     1     2     3     4     5     6     7     8    9    ...   410  \
0   0.524  45.1  34.1  72.8  10.3  34.1  44.3  23.6  15.8  8.2  ...  10.3   
1   0.317  45.4  36.7  75.0  13.0  27.2  40.3  19.8  15.7  7.2  ...  12.6   
2   0.341  44.1  31.7  74.3  14.0  31.3  45.3  18.9  15.4  6.1  ...  13.0   
3   0.537  46.4  37.1  71.5   9.2  31.6  40.9  24.5  14.9  8.1  ...  10.8   
4   0.451  45.4  35.6  77.2  12.3  29.9  42.2  22.0  14.9  7.3  ...  12.3   
5   0.341  43.3  33.5  77.6  12.1  30.6  42.7  20.1  16.5  7.6  ...  13.6   
6   0.463  45.8  36.3  78.1   8.7  31.3  40.0  24.9  15.3  8.3  ...  10.8   
7   0.366  44.4  32.9  76.1  11.9  28.2  40.1  19.2  15.9  7.4  ...  12.2   
8   0.573  45.8  36.6  73.7  10.6  29.4  40.0  20.2  12.8  7.4  ...  11.7   
9   0.537  46.2  35.2  77.9   9.3  30.0  39.3  22.0  13.6  6.1  ...  12.4   
10  0.299  44.9  33.3  79.0   9.9  33.4  43.3  24.0  16.2  7.8  ...  10.2   
11  0.569  46.8  37.3  81.2  10.6  35.1  45.6  24.1  13.2  7.0  ...   9.7   
12  0.159  44.1  31.2  71.1  13.4  28.5  41.9  19.7  16.1  7.7  ...  13.8   
13  0.610  45.5  33.2  75.6  13.5  29.5  43.0  19.1  14.8  7.9  ...  13.7   
14  0.606  45.4  37.0  74.0   9.9  31.3  41.2  22.4  14.0  8.1  ...  11.7   
15  0.427  44.4  35.2  79.3  11.4  31.2  42.6  20.5  16.7  7.5  ...  11.2   
16  0.293  44.6  36.0  78.5   9.1  32.8  41.9  23.7  15.5  7.8  ...  10.0   

     411   412   413   414  415  416   417   418  419  
0   32.6  42.9  23.9  14.2  8.5  4.1  21.3  19.8  1.8  
1   28.6  41.2  18.6  13.9  8.0  4.1  22.6  25.0  1.9  
2   29.7  42.7  21.6  16.1  7.2  4.7  26.2   2.7 -3.3  
3   32.3  43.2  21.6  15.1  7.3  4.6  20.5  19.1 -2.5  
4   29.3  41.6  19.6  13.2  7.7  4.8  19.6  20.2 -0.3  
5   29.2  42.8  18.7  17.5  8.9  5.0  20.9   0.0 -5.6  
6   31.4  42.2  23.3  14.7  8.1  4.6  20.4  19.5  1.3  
7   29.0  41.2  20.2  13.8  7.7  4.6  22.2  23.5 -0.5  
8   28.4  40.1  20.0  14.0  7.5  4.5  20.5  20.0 -7.5  
9   29.0  41.3  19.4  15.3  8.1  6.1  22.6  20.3 -7.4  
10  31.9  42.0  25.0  14.2  8.0  4.3  22.7  22.2 -4.7  
11  35.5  45.2  25.5  14.4  7.3  4.1  21.6  22.0 -1.8  
12  29.0  42.8  19.1  14.3  8.7  4.2  22.0   0.0 -0.3  
13  28.5  42.2  23.2  14.1  8.4  4.6  22.4   0.2  0.6  
14  29.9  41.7  19.1  15.3  8.0  6.3  21.3  18.7 -4.8  
15  29.2  40.4  19.7  13.4  7.6  4.8  20.0   0.0 -1.0  
16  33.1  43.1  25.2  14.6  7.9  4.3  21.3  20.0  0.6  

[17 rows x 420 columns]

In [79]:
indexGoatedTrain = [5,16,22,9,14,18,8,15,13,11,2,1,17,24,10,19,4]
ytrainGoat = []
for i in range(17):
    ytrainGoat.append(y[i])
ytrainGoat

[17, 14, 28, 10, 10, 6, 10, 27, 16, 16, 7, 14, 14, 2, 27, 16, 27]

In [81]:
dfsame["label"] = ytrainGoat
dfsame
dfgoat.to_csv(path_or_buf = '/Users/nanboo/Desktop/CS4700/ML-NBA-Predictor/data/goatedTrain.csv')